spring:
  boot:
    admin:
      client:
        url: http://192.168.1.116:8084
  application:
    name: cwj-itoken-config
  zipkin:
    base-url: http://192.168.1.116:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/cwjyun/spring-cloud
          search-paths: respo
          username: cwjyun@163.com
          password: 41127283asd

server:
  port: 8888


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/